name: Synchronization branchs

on:
  workflow_call: {}



jobs:
  sync-branches:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses:  actions/checkout@v4
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
         

      - name: Fetch all branches
        run: git fetch --prune --unshallow

      - name: Merge main -> develop
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        continue-on-error: true
        run: |
          git config --global user.name "davidoutside"
          git config --global user.email "david.vanzo@outsidethebox.ar"
          git checkout develop
          git merge main --no-ff --no-edit
          git push origin develop
          