name: Synchronization branchs

on:
  workflow_call: {}



jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses:  actions/checkout@v4
         
      - name: Merge main -> develop
        env:
          GIT_TOKEN: ${{ secrets.TEST_TOKEN }}
        continue-on-error: true
        run: |
          git config --global user.name "davidoutside"
          git config --global user.email "david.vanzo@outsidethebox.ar"
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/davidoutside/rank-test.git
          git fetch --prune --unshallow
          git checkout develop
          git merge main --no-ff --no-edit
          git push origin develop
          