name: Synchronization branchs

on:
  workflow_call: {}

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --prune --unshallow
      
        # Add git config as secret with a generic user.
      - name: Set git identity
        run: |
          git config --global user.email "david.vanzo@outsidethebox.ar"
          git config --global user.name "davidoutside"

      - name: Merge main -> develop
        continue-on-error: true
        run: |
          git checkout develop
          git merge main --no-ff --no-edit
          git push --set-upstream origin/develop
#        env:
#          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CHAK }}  