name: Synchronization branchs

on:
  workflow_call: {}

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Fetch all branches
        run: git fetch --prune --unshallow
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}  
      
        # Add git config as secret with a generic user.
      - name: Set git identity
        run: |
          git config --global user.email "david.vanzo@outsidethebox.ar"
          git config --global user.name "davidoutside"
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}  


      - name: Merge main -> develop
        continue-on-error: true
        run: |
          git checkout develop
          git merge main --no-ff --no-edit
          git remote set-url origin https://${{ secrets.TEST_TOKEN }}@github.com/davidoutside/rank-test.git
          git push origin develop
          
